# Generated by Django 3.2 on 2021-04-29 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
    ]
