# Generated by Django 3.2 on 2021-05-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(upload_to='./media'),
        ),
    ]
