# Generated by Django 3.2 on 2021-05-03 07:48

from django.db import migrations, models
import django.db.models.deletion
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_photos'),
        ('photos', '0003_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='albums.album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(upload_to=photos.models.get_location),
        ),
    ]
