# Generated by Django 3.2 on 2021-04-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
